// Sri Lanka first (most common default for this business), then likely
// tourist-origin countries, then the rest alphabetically.
export const countries = [
  { name: 'Sri Lanka', code: 'LK', dial: '+94' },
  { name: 'United Kingdom', code: 'GB', dial: '+44' },
  { name: 'United States', code: 'US', dial: '+1' },
  { name: 'Australia', code: 'AU', dial: '+61' },
  { name: 'Germany', code: 'DE', dial: '+49' },
  { name: 'France', code: 'FR', dial: '+33' },
  { name: 'Netherlands', code: 'NL', dial: '+31' },
  { name: 'India', code: 'IN', dial: '+91' },
  { name: 'China', code: 'CN', dial: '+86' },
  { name: 'Japan', code: 'JP', dial: '+81' },
  { name: 'Canada', code: 'CA', dial: '+1' },
  { name: 'Italy', code: 'IT', dial: '+39' },
  { name: 'Spain', code: 'ES', dial: '+34' },
  { name: 'Switzerland', code: 'CH', dial: '+41' },
  { name: 'Sweden', code: 'SE', dial: '+46' },
  { name: 'Norway', code: 'NO', dial: '+47' },
  { name: 'Denmark', code: 'DK', dial: '+45' },
  { name: 'Russia', code: 'RU', dial: '+7' },
  { name: 'South Korea', code: 'KR', dial: '+82' },
  { name: 'Singapore', code: 'SG', dial: '+65' },
  { name: 'Malaysia', code: 'MY', dial: '+60' },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971' },
  { name: 'Saudi Arabia', code: 'SA', dial: '+966' },
  { name: 'New Zealand', code: 'NZ', dial: '+64' },
  { name: 'South Africa', code: 'ZA', dial: '+27' },
  { name: 'Brazil', code: 'BR', dial: '+55' },
  { name: 'Argentina', code: 'AR', dial: '+54' },
  { name: 'Mexico', code: 'MX', dial: '+52' },
  { name: 'Israel', code: 'IL', dial: '+972' },
  { name: 'Ireland', code: 'IE', dial: '+353' },
  { name: 'Belgium', code: 'BE', dial: '+32' },
  { name: 'Austria', code: 'AT', dial: '+43' },
  { name: 'Portugal', code: 'PT', dial: '+351' },
  { name: 'Poland', code: 'PL', dial: '+48' },
  { name: 'Finland', code: 'FI', dial: '+358' },
  { name: 'Greece', code: 'GR', dial: '+30' },
  { name: 'Turkey', code: 'TR', dial: '+90' },
  { name: 'Thailand', code: 'TH', dial: '+66' },
  { name: 'Indonesia', code: 'ID', dial: '+62' },
  { name: 'Philippines', code: 'PH', dial: '+63' },
  { name: 'Vietnam', code: 'VN', dial: '+84' },
  { name: 'Pakistan', code: 'PK', dial: '+92' },
  { name: 'Bangladesh', code: 'BD', dial: '+880' },
  { name: 'Nepal', code: 'NP', dial: '+977' },
  { name: 'Maldives', code: 'MV', dial: '+960' },
  { name: 'Afghanistan', code: 'AF', dial: '+93' },
  { name: 'Albania', code: 'AL', dial: '+355' },
  { name: 'Algeria', code: 'DZ', dial: '+213' },
  { name: 'Bahrain', code: 'BH', dial: '+973' },
  { name: 'Bulgaria', code: 'BG', dial: '+359' },
  { name: 'Chile', code: 'CL', dial: '+56' },
  { name: 'Colombia', code: 'CO', dial: '+57' },
  { name: 'Croatia', code: 'HR', dial: '+385' },
  { name: 'Cyprus', code: 'CY', dial: '+357' },
  { name: 'Czech Republic', code: 'CZ', dial: '+420' },
  { name: 'Egypt', code: 'EG', dial: '+20' },
  { name: 'Estonia', code: 'EE', dial: '+372' },
  { name: 'Hong Kong', code: 'HK', dial: '+852' },
  { name: 'Hungary', code: 'HU', dial: '+36' },
  { name: 'Iceland', code: 'IS', dial: '+354' },
  { name: 'Iraq', code: 'IQ', dial: '+964' },
  { name: 'Jordan', code: 'JO', dial: '+962' },
  { name: 'Kenya', code: 'KE', dial: '+254' },
  { name: 'Kuwait', code: 'KW', dial: '+965' },
  { name: 'Latvia', code: 'LV', dial: '+371' },
  { name: 'Lebanon', code: 'LB', dial: '+961' },
  { name: 'Lithuania', code: 'LT', dial: '+370' },
  { name: 'Luxembourg', code: 'LU', dial: '+352' },
  { name: 'Malta', code: 'MT', dial: '+356' },
  { name: 'Mauritius', code: 'MU', dial: '+230' },
  { name: 'Myanmar', code: 'MM', dial: '+95' },
  { name: 'Nigeria', code: 'NG', dial: '+234' },
  { name: 'Oman', code: 'OM', dial: '+968' },
  { name: 'Qatar', code: 'QA', dial: '+974' },
  { name: 'Romania', code: 'RO', dial: '+40' },
  { name: 'Serbia', code: 'RS', dial: '+381' },
  { name: 'Slovakia', code: 'SK', dial: '+421' },
  { name: 'Slovenia', code: 'SI', dial: '+386' },
  { name: 'Taiwan', code: 'TW', dial: '+886' },
  { name: 'Ukraine', code: 'UA', dial: '+380' },
  { name: 'Uruguay', code: 'UY', dial: '+598' }
];